name: flutter_video
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter
  stream_chat_flutter: ^7.2.1
  stream_video_flutter: ^0.3.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
